#!/bin/bash
# Pre-removal script for ddogreen (DEB)

set -e

SERVICE_NAME="ddogreen"

case "$1" in
    remove|upgrade|deconfigure)
        echo "Stopping ddogreen service for removal..."
        
        # Stop the service (disable will be done in postrm)
        systemctl stop "$SERVICE_NAME" || true
        ;;
esac

exit 0
